sudo: false
language: ruby
cache: bundler

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
branches:
  only:
    - master

bundler_args: --without docs debug

before_install:
  - gem update bundler
  - gem update --system

script: bundle exec rake test
